name: Docker Image CI

on:
  push:
    branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

    inputs:
      changelog:
        description: "changelog"
        default: "- ddd"
        type: "string"
        required: true
      publish_artifacts:
        description: 'Publish artifacts'
        required: true
        default: 'false'
        type: boolean
      rel_type:
        type: choice
        description: Select type of release
        required: true
        default: 'dev'
        options:
          - dev
          - release
      test_number:
        type: number
        description: Select type of release
        default: 1
        required: true
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:

  checkout-test:

#    runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
    - id: env_info
      name: env_info
      run: |
        echo "GITHUB_ACTOR:      {{ GITHUB_ACTOR }}"
        echo "GITHUB_BASE_REF:   {{ GITHUB_BASE_REF }}"
        echo "GITHUB_JOB:        {{ GITHUB_JOB }}"
        echo "GITHUB_RUN_ID:     {{ GITHUB_RUN_ID }}"
        echo "GITHUB_RUN_NUMBER: {{ GITHUB_RUN_NUMBER }}"
        echo "RUNNER_NAME:       {{ RUNNER_NAME }}"
        echo "GITHUB_SHA:        {{ GITHUB_SHA }}"
    - id: checkout-private
      name: Checkout - Private
      run: |
        the_secret=$((RANDOM))
        echo "{secret-number}={$the_secret}" >> $GITHUB_OUTPUT
        echo "{name}={value}" >> $GITHUB_STATE

#        echo "::add-mask::$the_secret"

    - id: checkout-private2
      name: Checkout - Private2
      run: |
        date
        date -u
        pwd
        ls -al
        echo "the secret number is ${{ steps.sets-a-secret.outputs.secret-number }}"
        rm -rf asvsam-installer
        git clone https://github.com/asvsam/asvsam-installer.git
        ls -al
        find .
        (cd asvsam-installer; git rev-parse HEAD)
        (cd asvsam-installer; git rev-parse --short HEAD)
        NOW_UNIXTIME=$(date +%s)
        echo ${NOW_UNIXTIME}
        env
        (date +"%Y-%m-%d_%H-%M_%S_%N" -d "@${NOW_UNIXTIME}")
        (date -u +'%Y-%m-%dT%H:%M:%SZ' -d "@${NOW_UNIXTIME}")
        (date +"%y%m%d-%H%M" -d "@${NOW_UNIXTIME}")
        pwd
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
#      run: echo "${{ secrets.DOCKERHUB_USERNAME }}" > ddd;cat ddd; ls -al ddd;git clone https://github.com/asvsam/asvsam-installer.git;ls -al; find asvsam-installer

  build:
    needs: checkout-test
    runs-on: self-hosted
    # Approval Step
    environment: Release

    steps:
    -
      name: Checkout
      uses: actions/checkout@v3

#     -
#       name: Build the Docker image
#       run: docker build . --file Dockerfile --tag debian-builder:$(date +%s)

    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    -
      name: Run shell command
      run: pwd; id; hostname; ls -al; echo $DOCKERHUB_USERNAME; echo ${{ secrets.DOCKERHUB_USERNAME }}; echo ${{ inputs.changelog }}; echo "${{ github.event.inputs.publish_artifacts }} __"
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

    - name: Configure GPG Key
      run: . ./build_helper.sh; config_gpg
      env:
        GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/debian-builder:latest

    - if: github.event.inputs.publish_artifacts == 'true'
      name: Publish Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: build/web
